---
- name: Install Lib
  apt: name={{ item }} state=latest
  with_items:
    - postgresql 
    - postgresql-contrib
    - python-psycopg2
    - libpq-dev

- name: enable and Start postgresql
  service:
    name: postgresql
    state: started
    enabled: yes

- name: create database
  become_user: postgres
  postgresql_db:
    name: test_development

- name: create user of database
  become_user: postgres
  postgresql_user:
    db: test_development
    name: vagrant
    password: password

- name: grant user for database
  become_user: postgres
  postgresql_privs:
    db: test_development
    state: present
    priv: ALL
    objs: ALL_IN_SCHEMA
    role: vagrant
  