---
- name: Install Lib
  apt: name={{ item }} state=latest
  with_items:
    - postgresql 
    - postgresql-contrib
    - python-psycopg2
    - libpq-dev

- name: enable and Start postgresql
  service:
    name: postgresql
    state: started
    enabled: yes

- name: create database
  become_user: postgres
  postgresql_db:
    name: "{{ database.name }}"

- name: create user of database
  become_user: postgres
  postgresql_user:
    db:       "{{ database.name }}"
    name:     "{{ database.user }}"
    password: "{{ database.password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER

- name: grant user for database
  become_user: postgres
  postgresql_privs:
    db:    "{{ database.name }}"
    state: present
    priv:  ALL
    objs:  ALL_IN_SCHEMA
    role:  vagrant
  