---
- name: Ansible check versions {{ ruby.version }} exists.
  stat:
    path: "{{ project_dir }}"
  register: dir_project

- name: clone project
  git: 
    repo: "{{ repo }}"
    dest: "{{ project_dir }}"
  when: dir_project.stat.exists == False

- name: Change permission
  file:
    path: "{{ project_dir }}"
    owner: vagrant
    group: vagrant
    recurse: yes

- name: copy file database.yml
  copy:
    src: templates/database.yml
    dest: "{{ project_dir }}/config/database.yml"
    owner: vagrant
    group: vagrant